### ISSUE TITLE
Timer and Progress Bar in Color Game

### ISSUE THREAD

**Issue by jfngc** [human-nature-lab/breadboard-archive#14]
I'm having trouble getting a timer and the bonus progress bar to run at the same time. Is there an example of this implemented in another game?

**Comment by disperse** [comment]
There is an issue where a change to the timers will not trigger breadboard to send an update to the client. To work around this issue, make sure to change another property of the vertex after adding the timers, for example:

```
g.addTimer(time: 15, type: "time", appearance: "danger", timerText: "This timer goes up", direction: "up", result: { player-> player.text = "Hello" })
g.addTimer(time: 20, type: "time", appearance: "info", timerText: "This timer goes down", direction: "down", result: { player-> player.text = "world!" })
g.V.each { v-> v.text = "Testing" }
```

I tested this code with v2.2.4, let me know if this doesn't work for you.

The issue with changes to timers not being updated will be fixed in v2.3.
